- README.md
I have added a very basic README example for the q.Q snippet for VSCODE. If you would like something more expansive let me know.
> Adding VSCODE snippet example to README

- q.sh
Sweet little library that you've got here.
Patch is to make q.sh correctly find the output file in the cases where TMPDIR does not end in a trailing slash. Admittedly, this happened because I had to manually set TMPDIR within a docker container and just didn't add it.
When TMPDIR=/tmp then logpath=/tmpq despite the go library correctly writing to /tmp/q. With this change logpath=/tmp/q when TMPDIR=/tmp, and logpath=/tmp//q when TMPDIR=/tmp/ which still works just fine.
Hope this is useful 👍
> q.sh: Handle TMPDIR without trailing slash

- README.md
GOPATH is a list of directories, not a single directory, as documented at
https://golang.org/cmd/go/#hdr-GOPATH_environment_variable . This change
fixes the qq alias to handle it correctly in Unix environments.
The lack of Windows support in the fix should be fine since the original
alias was already broken on Windows.
> Fix GOPATH handling in qq alias

- .travis.yml
Go 1.9 tools ignore `vendor/`. Dropping testing with older versions of Go lets us replace all those ugly `grep -v /vendor/` commands and just use `./...`, e.g. `go test ./...`. The exception to this is naughty `golint`, [which still doesn't ignore `vendor/`](https://github.com/golang/lint/pull/325).
> Update travis to only test on Go 1.9

- helpers.go
- helpers_test.go
Would panic in cases where the Obj for an Ident was nil. Not
sure when this applies (in general) but one case was given in
from a test file.
Fixes #15
> argName: Handle *ast.Ident with nil Obj

- logger.go
- logger_test.go
- q.go
`q.Q()` calls in the same function in the same file that occur within 2s of each other are grouped under the same header.
```
[14:00:36 main.go main.main:122]
```
I was using a `*time.Timer` object to track the 2s intervals to determine if a new header line needed to be printed. This is a somewhat complicated object that uses a channel internally. It's simpler and faster to replace the timer object with a timestamp for tracking the time since the last write. This enables me to remove `init()`.
I also moved the logger type and methods to a separate `logger.go` file.
> Replace timer with lastWrite timestamp

- args.go
on defer "names" is empty so we range over "values".
https://github.com/y0ssar1an/q/pull/26
> fix #9 defer Q() not printing output.

- README.md
This PR fixes `rmqq` command in the sh script for when `$TMPDIR` is unset.
> Fix `rmqq` sh script

- .circleci/config.yml
* use executors to DRY out some of the CircleCI config
* use `/go/pkg` cache when building linter
* cut CI times by 5-10s
> Improve caching of Go pkgs on CircleCI

- .circleci/config.yml
This lets us delete the `-mod=vendor` flag in two places
> Set $GOFLAGS to '-mod=vendor'

- logger.go
- logger_test.go
- q.go
- Inline the `bytes.Buffer` into the `logger` struct to avoid one level of pointer indirection.
- Declare the singleton logger without pointer indirection
> Inline buffer in logger to avoid pointer indirection

- .circleci/config.yml
- README.md
* update CI to use the golang:1.12 container.
* change the install instructions in the README to `GO111MODULE=off go get github.com/y0ssar1an/q` so the old `go get` behavior will be used.
> Fetch golangci-lint in CircleCI config

- .circleci/config.yml
- .github/workflows/main.yml
- .golangci.yml
- args.go
- args_test.go
- logger_test.go
* run the linter from its own container
* update the linter to v1.21.0
* disable the new `wsl` linter
* This is an opinionated linter about whitespace. It's really not necessary
* change `deadline` to `timeout` in the CircleCI config
* The name of the key changed
* update the linter in the GitHub Actions CI config too
> Update the CircleCI config

- go.mod
Using go1.13.7 for building my project (that uses github.com/y0ssar1an/q as a dependency) I got the error:
```
github.com/y0ssar1an/q@v1.0.8 requires
github.com/golangci/golangci-lint@v1.12.2 requires
github.com/golangci/tools@v0.0.0-20180902102414-2cefd77fef9b: invalid version: unknown revision 2cefd77fef9b
```
I've cloned the repository, made local changes in go.mod (just set up go1.13)
```diff --git a/go.mod b/go.mod
index 86f936a..092e9a3 100644
--- a/go.mod
+++ b/go.mod
@@ -1,5 +1,5 @@
module github.com/y0ssar1an/q
-go 1.12
+go 1.13
require github.com/kr/pretty v0.2.0
(END)
```
used the 'replace' in my project's go.mod (from github.com/y0ssar1an/q to local copy) - and that helped.
At the same time, it works without any go.mod changes when I used go1.12.13 for the project build.
Also, …
> Go1.13 build fix: go.mod: go1.12 => go1.13

- .circleci/config.yml
- .github/workflows/main.yml
- README.md
- go.mod
- vendor/modules.txt
- Update required `go` version in `go.mod` to 1.14
- Update CI runners to use `golang:1.14` image
- Remove `-mod=vendor` and `GO111MODULE=on` flags from everywhere
> Update to Go 1.14

- README.md
- doc.go
- go.mod
- go.sum
- testdata/sample1.go
- vendor/github.com/kr/text/go.mod
- vendor/modules.txt
Resolve #54. It's annoying to type y0ssar1an.
Update README. Replace full github import with just `import "q"`
Vendor `github.com/kr/text`, which `go mod tidy` wants now for some reason.
> Change pkg name from y0ssar1an/q to ryboe/q

- .circleci/config.yml
- .golangci.yml
- args.go
- args_test.go
- logger.go
Change some wrapped errors to use `%w` instead of `%v`.
Disable `testpackage` linter, because whitebox testing should be allowed.
> Update golangci-lint v1.24 -> v1.27

- .circleci/config.yml
- logger.go
Format `logger.go` with `gofumports`. This nit was flagged by the updated linter. `logger.go` now uses Go's new octal literal syntax, e.g. `0o600` instead of `0600`.
> Update golangci-lint v1.27.0 -> v1.28.0

- go.mod
- go.sum
- vendor/github.com/kr/text/go.mod
- vendor/modules.txt
I think [`kr/text`](https://github.com/kr/text) added a `go.mod` file, so that removes the `// indirect` import from q's `go.mod`.
> Clean up go.mod and go.sum

- README.md
Badges were finally added to `pkg.go.dev` (details [here](https://github.com/golang/go/issues/36982#issuecomment-658403591)).
> Replace godoc badge with pkg.go.dev badge

- .circleci/config.yml
- .golangci.yml
- args.go
- logger.go
* Use convencience wrapper `strings.ReplaceAll()` instead of `strings.Replace(..., -1)`. This was caught by `gocritic`.
* Disable new linter `exhaustivestruct`. It requires that all fields in a struct be set. That check is only useful in certain situations.
> Update golangci-lint 1.30 -> 1.32

- .golangci.yml
- args.go
Enable [all the `gocritic` checks](https://go-critic.github.io/overview) except [`whyNoLint`](https://go-critic.github.io/overview#whyNoLint-ref). I tried adding explanations to a few nolints, but `gocritic` didn't recognize that an explanation had been added. It kept complaining.
> Enable all gocritic checks

- .circleci/config.yml
- .golangci.yml
* update `golangci-lint` v1.32.0 -> v1.33.0
* reduce `gocyclo`'s max complexity to 10, which is a nice round number
> Update golangci-lint 1.32 -> 1.33

- .circleci/config.yml
- args_test.go
* Bump `golangci-lint` v1.34 -> v1.35
* Suppress `thelper` linter in two places
* erroneously suggested that two subtests could be test helpers
> Update golangci-lint to 1.35

- .circleci/config.yml
- go.mod
* Bump the go directive in go.mod to `go 1.16`
* Bump golangci-lint 1.35.0 -> 1.36.0
I'm just waiting for the final 1.16 release to Docker Hub.
> Update to Go 1.16

- README.md
The _Open in VS Code_ badge was supported in the 1.58 release of VS Code. The feature is described [here](https://code.visualstudio.com/updates/v1_58#_open-in-vs-code-badge).
> Add 'Open in VS Code' badge to README

- .circleci/config.yml
- .golangci.yml
- args_test.go
Disable deprecated linters:
* golint
* interfacer
* maligned
* scopelint
> Bump golangci-lint 1.37 -> 1.41

- README.md
The GOPATH environment variable is not a sure thing anymore. https://golang.org/doc/gopath_code#GOPATH
> A more reliable way to get GOPATH

- .circleci/config.yml
- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .golangci.yml
This is a first attempt to add an Arch Linux-based codespace to this repo. It includes a `devcontainer.json` file and a `Dockerfile` defining an image with a custom Go environment.
> Add devcontainer and a Dockerfile based on ryboe/archcodespace

- README.md
I don't know why the badge icon is broken, but it's not a big deal.
> Remove broken "Open in VS Code" badge

- .devcontainer/Dockerfile
I moved a lot of the steps in dev container Dockerfile to a dedicated
base image called ryboe/alpinecodespace.
> Use ryboe/alpinecodespace as a codespace base image to avoid customizations

- .github/workflows/pr.yml
- README.md
* rename `Test` workflow to `PR`
There's no reason to run tests on `master` when the identical commit has already been tested when it was a PR (pre-merge). Also, it should be
expected that `master` always passes tests. Since only rebase merging is allowed, we can guarantee that the commit on `master` has been tested by requiring that status checks pass in the repo settings on GitHub.
> Remove CI status badge from README

- args.go
- q.go
Being able to set the `runtime.Caller(CallDepth)` might be useful in certain use cases explained in the code comment.
For most, if not all cases, calls to `q.Q` should be removed before releasing code. One way to do this is to check for occurrences of `q.Q` in code during code review or performing static analysis. 
This change takes a slightly different approach, allowing the `CallDepth` to be set, so that wrapping code can perform checks before calling into the `q.Q` code. For example, the wrapping code could constrain usage to non-production builds, ensuring `q.Q` isn't executed when it shouldn't.
This is useful to me personally, but I can understand if it doesn't get merged.
> Make the `runtime.Caller(CallDepth)` configurable

- .devcontainer/devcontainer.json
There's a bug which causes extensions to install excruciatingly slowly in devcontainers on Apple Silicon Macs. The bug is somehow related to [extension verification checks](https://github.com/microsoft/vscode/issues/179827). For now, we'll disable extension verification in the VS Code settings for devcontainers only.
> fix: Painfully slow extension install in devcontainer on Apple Silicon

- .devcontainer/devcontainer.json
- .vscode/settings.json
This is the list of enabled analyzers:
fieldalignment
nilness
unusedparams
unusedvariable
unusedwrite
useany
The analyzers that weren't enabled have too high a risk of false positives.
> feat: Enable gopls static analyzers

- .github/workflows/pr.yml
- go.mod
- go.sum
- vendor/modules.txt
Also bump the `github.com/rogpeppe/go-internal` indirect dep from 1.11 to 1.12.
Also fix CI by making actions/setup-go fetch the Go version from the go.mod file.
> chore: update go.mod to use go 1.22

- .devcontainer/devcontainer.json
- .github/workflows/codeql-analysis.yml
- .github/workflows/pr.yml
- .golangci.yml
- .vscode/extensions.json
- args_test.go
- go.mod
- logger.go
* remove gitlens from list of recommended extensions
* update golangci-lint action
* update codeql analysis action v2 -> v3
* remove deprecated extensions that were disabled in
.golangci.yml
* name magic number octal literal in logger.go
* use new for-range over integers syntax
* bump go directive to 1.23
> chore: aug 2024 maintenance pass

- .github/workflows/codeql-analysis.yml
- .github/workflows/pr.yml
- .golangci.yml
- args_test.go
* `dominickh`, the author of [`staticcheck`](https://github.com/dominikh/go-tools), doesn't recommend running staticcheck as a part of golangci-lint. Run the real, official `staticcheck` separately.
* run `go vet` separately as well. This way we know we're using the latest official `go vet` tool
* use `autobuild` to set up Go in the CodeQL analysis workflow
* rewrite `TestExtractingArgsFromSourceText` to avoid use of deprecated `ast.Object` type
* use [`WillAbides/setup-go-faster`](https://github.com/WillAbides/setup-go-faster) instead of `actions/setup-go` because it's faster
> ci: run go vet and staticcheck separately
